version: '3'
services:
    zoo1:
        build: .
        image: bdcloud/zookeeper
        restart: always
        container_name: zoo1
        ports:
            - "2181:2181"
        volumes:
          - /opt/zookeeper/data1:/data
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: bdcloud/zookeeper
        restart: always
        container_name: zoo2
        links:
            - zoo1
        ports:
            - "2182:2181"
        volumes:
          - /opt/zookeeper/data2:/data
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: bdcloud/zookeeper
        restart: always
        container_name: zoo3
        links:
            - zoo1
        ports:
            - "2183:2181"
        volumes:
          - /opt/zookeeper/data3:/data
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
